# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - TOXENV=py34-1.8.X,py32-1.8.X,py33-1.8.X,py27-1.8.X
  - TOXENV=py34-1.7.X,py32-1.7.X,py33-1.7.X,py27-1.7.X
  - TOXENV=py34-1.6.X,py32-1.6.X,py33-1.6.X,py27-1.6.X
  - TOXENV=flake8
  - TOXENV=coverage
  - TOXENV=docs

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success: coveralls $COVERALLS_OPTION
